name: merge Staging

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  buildServer:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          push: true
          image: dart_backend_docker_test
          tags:  ghcr.io/levchenkoroman/dart_backend_docker_test
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}