name: merge Staging

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  buildServer:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          push: true
          image: dart_backend_docker_test
          tags:  ghcr.io/levchenkoroman/dart_backend_docker_test
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old images
        uses: snok/container-retention-policy@v1
        with:
          image-names: dart_backend_docker_test*
          keep-at-least: 2
          account-type: personal #org or personal
          token: ${{ secrets.PAT_TOKEN }}
          cut-off: now UTC
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none
          DRY_RUN: true
          RELEASE_BRANCHES: master
          INITIAL_VERSION: 1.0.0
          VERBOSE: true

